const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ico=n=>`<svg><use href="#${n}"/></svg>`;
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const app={workspace:null,defaults:null,fonts:[],latest:"",selected:new Set(),page:0,saveTimer:0,previewTimer:0,previewSeq:0,staged:null,busy:false,output:null};

function defaultFields(d){return(d.fields||[]).map((field,index)=>({id:`field-${index+1}`,sourceIndex:index,letter:"",sourceName:field.name,label:field.name,included:true,password:Boolean(field.password),truncate:Boolean(field.truncate)}))}
function fresh(d){return{version:4,sourceName:"",sheets:[],sheet:"",headers:[],columns:defaultFields(d),fieldProfile:[],rows:[],rules:[],savedRuleSets:d.savedRuleSets||[],fillRules:[],mappingPreferences:{},design:{...d.design},blankSlips:0,outputFolder:d.outputFolder||"~/Downloads",emailAddress:d.emailAddress||"",extraSummaryColumns:[],importPreferences:{excludeHidden:true,mode:"replace"}}}
function hydrate(saved,d){const base=fresh(d);if(!saved||typeof saved!=="object")return base;const emptyLegacy=!saved.sourceName&&!(saved.rows||[]).length;return{...base,...saved,design:{...base.design,...(saved.design||{})},columns:emptyLegacy?base.columns:(Array.isArray(saved.columns)&&saved.columns.length?saved.columns:base.columns),fieldProfile:Array.isArray(saved.fieldProfile)?saved.fieldProfile:[],rows:Array.isArray(saved.rows)?saved.rows:[],rules:Array.isArray(saved.rules)?saved.rules:[],savedRuleSets:Array.isArray(saved.savedRuleSets)?saved.savedRuleSets:base.savedRuleSets,fillRules:Array.isArray(saved.fillRules)?saved.fillRules:[],mappingPreferences:saved.mappingPreferences&&typeof saved.mappingPreferences==="object"?saved.mappingPreferences:{},importPreferences:{...base.importPreferences,...(saved.importPreferences||{})}}}
async function api(path,body){const o=body===undefined?{}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)};const r=await fetch(path,o),data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||"That action could not be completed.");return data}
function toast(message,error=false){const el=document.createElement("div");el.className=`toast${error?" error":""}`;el.textContent=message;$("#toastRegion").append(el);setTimeout(()=>el.remove(),3000)}
function busy(value){app.busy=value;["#previewPdfButton","#exportButton","#openButton","#emailButton"].forEach(s=>$(s).disabled=value);document.body.style.cursor=value?"progress":""}
function save(){clearTimeout(app.saveTimer);app.saveTimer=setTimeout(()=>api("/api/workspace",{workspace:app.workspace}).catch(e=>toast(e.message,true)),350)}
function changed(full=true){syncFieldProfile();app.output=null;$("#outputTicket").hidden=true;save();if(full)render();else queuePreview()}
function columns(){return app.workspace.columns.filter(c=>c.included)}
function nameKey(value){return String(value||"").trim().toLowerCase().replace(/\s+/g," ")}
function syncFieldProfile(){if(!app.workspace?.columns?.length)return;app.workspace.fieldProfile=app.workspace.columns.filter(c=>c.sourceName).map((c,order)=>({name:c.sourceName,label:c.label,included:Boolean(c.included),password:Boolean(c.password),truncate:Boolean(c.truncate),order}))}
function sourceColumn(i){return app.workspace.columns.find(c=>Number(c.sourceIndex)===Number(i))}
function normalizeRule(r){const named=r.columnName?app.workspace.columns.find(c=>nameKey(c.sourceName)===nameKey(r.columnName)):null;return{...r,columnIndex:named?Number(named.sourceIndex):Number(r.columnIndex??0),operator:r.operator||"is"}}
function matches(row,raw){const r=normalizeRule(raw),value=String(row.values?.[r.columnIndex]??"").trim(),wanted=String(r.value??"").trim();if(r.operator==="isNot")return value!==wanted;if(r.operator==="contains")return value.toLowerCase().includes(wanted.toLowerCase());if(r.operator==="empty")return !value;return value===wanted}
function passes(row){return app.workspace.rules.every(r=>matches(row,r))}
function printable(){return app.workspace.rows.filter(r=>r.included!==false&&passes(r))}
function visible(){const q=$("#rowSearch").value.trim().toLowerCase();return app.workspace.rows.filter(r=>passes(r)&&(!q||r.values.some(v=>String(v).toLowerCase().includes(q))))}
function job(){return{...app.workspace,rowsToPrint:printable(),blankSlips:Number(app.workspace.blankSlips)||0}}

function render(){renderFile();renderTable();renderFields();renderRules();bindValues();queuePreview()}
function renderFile(){$("#fileName").textContent=app.workspace.sourceName||"Import a workbook";$("#fileMeta").textContent=app.workspace.sourceName?`${app.workspace.sheet||"Sheet"} · ${app.workspace.rows.length} editable rows`:(app.latest?`Latest: ${app.latest.split(/[\\/]/).pop()}`:"Excel becomes editable rows")}
function renderTable(){const cols=columns(),rows=visible();$("#rowCount").textContent=printable().length;$("#tableEmpty").hidden=app.workspace.rows.length>0;$("#tableHead").innerHTML=`<tr><th class="check-cell"><input id="checkAll" type="checkbox"></th><th class="row-cell">Row</th><th>Print</th>${cols.map(c=>`<th>${esc(c.label)}</th>`).join("")}<th></th></tr>`;$("#tableBody").innerHTML=rows.map(r=>`<tr data-row="${esc(r.id)}" class="${r.included===false?"excluded ":""}${app.selected.has(r.id)?"selected":""}"><td class="check-cell"><input class="pick" type="checkbox" ${app.selected.has(r.id)?"checked":""}></td><td class="row-cell">${r.added?"NEW":esc(r.rowNumber)}</td><td class="check-cell"><input class="include" type="checkbox" ${r.included!==false?"checked":""}></td>${cols.map(c=>`<td class="data-cell"><input type="text" data-index="${c.sourceIndex}" value="${esc(r.values[c.sourceIndex]||"")}"></td>`).join("")}<td class="check-cell"><button class="row-action" title="Delete">${ico("trash")}</button></td></tr>`).join("");
  $$("tr[data-row]",$("#tableBody")).forEach(tr=>{const r=app.workspace.rows.find(x=>x.id===tr.dataset.row);$(".pick",tr).onchange=e=>{e.target.checked?app.selected.add(r.id):app.selected.delete(r.id);renderTable()};$(".include",tr).onchange=e=>{r.included=e.target.checked;changed()};$$("input[data-index]",tr).forEach(input=>input.oninput=e=>{r.values[Number(e.target.dataset.index)]=e.target.value;changed(false)});$(".row-action",tr).onclick=()=>{app.workspace.rows=app.workspace.rows.filter(x=>x.id!==r.id);app.selected.delete(r.id);changed()}});
  const all=$("#checkAll");if(all)all.onchange=e=>{rows.forEach(r=>e.target.checked?app.selected.add(r.id):app.selected.delete(r.id));renderTable()};renderBulk()}
function renderBulk(){const count=app.selected.size;$("#bulkBar").hidden=!count;$("#selectionCount").textContent=`${count} selected`}
function renderFields(){ensureFieldCreator();const list=$("#fieldList");$("#fieldCount").textContent=columns().length;list.innerHTML=app.workspace.columns.map((c,i)=>`<div class="field-card ${c.included?"":"off"}" data-id="${esc(c.id)}"><span class="field-letter">${i+1}</span><input class="field-name" value="${esc(c.label)}"><button class="field-toggle ${c.password?"active":""}" data-action="password" title="Password font">*</button><button class="field-toggle ${c.truncate?"active":""}" data-action="truncate" title="May truncate">−</button><input class="field-include" type="checkbox" ${c.included?"checked":""}><div class="order"><button data-move="-1" ${i===0?"disabled":""}>↑</button><button data-move="1" ${i===app.workspace.columns.length-1?"disabled":""}>↓</button></div></div>`).join("");$$(".field-card",list).forEach(card=>{const c=app.workspace.columns.find(x=>x.id===card.dataset.id);$(".field-name",card).oninput=e=>{c.label=e.target.value;changed(false)};$(".field-include",card).onchange=e=>{c.included=e.target.checked;changed()};$$("[data-action]",card).forEach(b=>b.onclick=()=>{c[b.dataset.action]=!c[b.dataset.action];changed()});$$("[data-move]",card).forEach(b=>b.onclick=()=>{const from=app.workspace.columns.indexOf(c),to=from+Number(b.dataset.move);app.workspace.columns.splice(from,1);app.workspace.columns.splice(to,0,c);changed()})});fillSelects()}
function ensureFieldCreator(){if($("#fieldCreator"))return;const form=document.createElement("div");form.id="fieldCreator";form.className="field-creator";form.innerHTML='<input id="newFieldName" placeholder="New field"><button id="createField" class="button primary small">Add</button>';$("#fieldList").insertAdjacentElement("beforebegin",form);$("#createField").onclick=()=>{const name=$("#newFieldName").value.trim();if(!name)return;const index=Math.max(-1,...app.workspace.columns.map(c=>Number(c.sourceIndex)))+1;app.workspace.columns.push({id:`field-${Date.now()}`,sourceIndex:index,sourceName:name,label:name,included:true,password:false,truncate:false});$("#newFieldName").value="";changed()};$("#newFieldName").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();$("#createField").click()}}}
function fillSelects(){const opts=app.workspace.columns.map(c=>`<option value="${c.sourceIndex}">${esc(c.letter)} · ${esc(c.label)}</option>`).join("");["#ruleColumn","#bulkColumn"].forEach(s=>{const el=$(s),old=el.value;el.innerHTML=opts;if([...el.options].some(o=>o.value===old))el.value=old});ruleValues()}
function ruleValues(){const i=Number($("#ruleColumn").value||0),values=[...new Set(app.workspace.rows.map(r=>String(r.values[i]||"").trim()).filter(Boolean))].slice(0,250);$("#ruleValues").innerHTML=values.map(v=>`<option value="${esc(v)}">`).join("")}
function ruleText(raw){const r=normalizeRule(raw),c=sourceColumn(r.columnIndex),op={is:"=",isNot:"≠",contains:"contains",empty:"is empty"}[r.operator]||"=";return `${c?.label||"Field"} ${op}${r.operator==="empty"?"":` ${r.value}`}`}
function renderRules(){$("#ruleCount").textContent=app.workspace.rules.length+app.workspace.fillRules.length;$("#ruleChips").innerHTML=app.workspace.rules.map((r,i)=>`<div class="rule-chip"><span>${esc(ruleText(r))}</span><button data-remove="${i}">×</button></div>`).join("");$$('[data-remove]',$("#ruleChips")).forEach(b=>b.onclick=()=>{app.workspace.rules.splice(Number(b.dataset.remove),1);changed()});$("#savedRules").innerHTML=app.workspace.savedRuleSets.map((set,i)=>`<div class="saved-rule"><button data-apply="${i}"><b>${esc(set.name||"Quick rule")}</b><small>${esc((set.rules||[]).map(ruleText).join(" · "))}</small></button><button data-delete="${i}">×</button></div>`).join("");$$('[data-apply]',$("#savedRules")).forEach(b=>b.onclick=()=>{app.workspace.rules=JSON.parse(JSON.stringify(app.workspace.savedRuleSets[Number(b.dataset.apply)].rules||[]));changed()});$$('[data-delete]',$("#savedRules")).forEach(b=>b.onclick=()=>{app.workspace.savedRuleSets.splice(Number(b.dataset.delete),1);changed()});renderFillRules()}
function fieldByName(fields,name){return fields.find(field=>nameKey(field.sourceName)===nameKey(name))}
function fillMatches(row,rule,fields){if(!rule.whenField)return true;const field=fieldByName(fields,rule.whenField);if(!field)return false;const value=String(row.values[field.sourceIndex]||""),wanted=String(rule.whenValue||"");if(rule.operator==="empty")return !value.trim();if(rule.operator==="contains")return value.toLowerCase().includes(wanted.toLowerCase());if(rule.operator==="isNot")return value.trim()!==wanted.trim();return value.trim()===wanted.trim()}
function applyFillRules(rows,fields){app.workspace.fillRules.forEach(rule=>{const target=fieldByName(fields,rule.targetField);if(!target)return;rows.filter(row=>fillMatches(row,rule,fields)).forEach(row=>{row.values[target.sourceIndex]=rule.setValue||""})})}
function ensureFillRuleUI(){if($("#fillRuleForm"))return;const section=document.createElement("section");section.className="fill-section";section.innerHTML='<div class="fill-title"><b>Fill values</b><button id="applyFillRules" class="link">Apply to current rows</button></div><div id="fillRuleForm" class="fill-form"><select id="fillWhenField"></select><select id="fillOperator"><option value="is">is</option><option value="isNot">is not</option><option value="contains">contains</option><option value="empty">is empty</option></select><input id="fillWhenValue" placeholder="When value"><select id="fillTarget"></select><input id="fillSetValue" placeholder="Set value"><button id="addFillRule" class="button primary small">Add fill rule</button></div><div id="fillRuleList" class="rule-list"></div>';$("#rulesPanel").append(section);$("#addFillRule").onclick=()=>{const target=fieldByName(app.workspace.columns,$("#fillTarget").value);if(!target)return toast("Choose a target field",true);app.workspace.fillRules.push({whenField:$("#fillWhenField").value,operator:$("#fillOperator").value,whenValue:$("#fillWhenValue").value,targetField:target.sourceName,setValue:$("#fillSetValue").value});changed()};$("#applyFillRules").onclick=()=>{applyFillRules(app.workspace.rows,app.workspace.columns);changed();toast("Fill rules applied")}}
function renderFillRules(){ensureFillRuleUI();const fields=app.workspace.columns,options=fields.map(field=>`<option value="${esc(field.sourceName)}">${esc(field.label)}</option>`).join("");$("#fillWhenField").innerHTML='<option value="">All rows</option>'+options;$("#fillTarget").innerHTML=options;$("#fillRuleList").innerHTML=app.workspace.fillRules.map((rule,i)=>`<div class="rule-chip"><span>${esc(rule.whenField?`${rule.whenField} ${rule.operator} ${rule.whenValue}`:"All rows")} → ${esc(rule.targetField)} = ${esc(rule.setValue)}</span><button data-fill-remove="${i}">×</button></div>`).join("");$$('[data-fill-remove]',$("#fillRuleList")).forEach(button=>button.onclick=()=>{app.workspace.fillRules.splice(Number(button.dataset.fillRemove),1);changed()})}
function bindValues(){$$('[data-design]').forEach(el=>{const key=el.dataset.design,val=app.workspace.design[key];if(el.type==="checkbox")el.checked=Boolean(val);else if(val!==undefined)el.value=val});$("#blankSlips").value=app.workspace.blankSlips||0;$("#outputFolder").value=app.workspace.outputFolder||"";$("#emailAddress").value=app.workspace.emailAddress||"";$("#extraSummaryColumns").value=(app.workspace.extraSummaryColumns||[]).join(", ")}

function queuePreview(){clearTimeout(app.previewTimer);if(!columns().length||(!printable().length&&!Number(app.workspace.blankSlips))){$("#previewLabel").textContent="Add rows or blank slips";stats({rows:0,slips:0,pages:0,perPage:0});return}app.previewTimer=setTimeout(loadPreview,180)}
async function loadPreview(){const seq=++app.previewSeq;try{const data=await api("/api/preview",{workspace:job(),page:app.page});if(seq!==app.previewSeq)return;app.page=data.page;$("#svgPreview").innerHTML=data.svg;$("#previewLabel").textContent=app.workspace.sheet||"Editable workspace";$("#previewPosition").textContent=`${data.page+1} / ${Math.max(1,data.slipPages)}`;stats(data)}catch(e){if(seq===app.previewSeq){$("#previewLabel").textContent=e.message;stats({rows:printable().length,slips:0,pages:0,perPage:0})}}}
function stats(d){$("#statRows").textContent=d.rows||0;$("#statSlips").textContent=d.slips||0;$("#statPages").textContent=d.pages||0;$("#statPerPage").textContent=d.perPage||0}

function prepareImport(data){const sources=data.columns,preferences=app.workspace.mappingPreferences||{};data.sourceColumns=sources;data.fields=JSON.parse(JSON.stringify(app.workspace.columns));data.mappings={};data.fields.forEach(field=>{const preferred=preferences[nameKey(field.sourceName)]||field.sourceName;const match=sources.find(source=>nameKey(source.sourceName)===nameKey(preferred))||sources.find(source=>nameKey(source.sourceName)===nameKey(field.label));data.mappings[field.id]=match?match.sourceName:""});return data}
function ensureImportFields(){let box=$("#importFields");if(box)return box;box=document.createElement("div");box.id="importFields";box.className="import-fields";$("#importCount").insertAdjacentElement("afterend",box);return box}
function renderImportFields(){const box=ensureImportFields(),options='<option value="">Leave blank</option>'+app.staged.sourceColumns.map(c=>`<option value="${esc(c.sourceName)}">${esc(c.letter)} · ${esc(c.sourceName)}</option>`).join("");box.innerHTML='<div class="mapping-head"><span>Slip field</span><span>Excel column</span></div>'+app.staged.fields.map((field,i)=>`<label class="import-field" data-index="${i}"><span><b>${esc(field.label)}</b><small>${field.password?"password":"field"}</small></span><span class="map-arrow">←</span><select>${options}</select></label>`).join("")+'<button id="addUnmapped" class="link">Add unmapped Excel columns as fields</button>';$$('.import-field',box).forEach(row=>{const field=app.staged.fields[Number(row.dataset.index)],select=$("select",row);select.value=app.staged.mappings[field.id]||"";select.onchange=()=>{app.staged.mappings[field.id]=select.value}});$("#addUnmapped").onclick=()=>{const used=new Set(Object.values(app.staged.mappings).map(nameKey));app.staged.sourceColumns.filter(source=>!used.has(nameKey(source.sourceName))).forEach(source=>{const index=Math.max(-1,...app.staged.fields.map(c=>Number(c.sourceIndex)))+1,field={id:`field-${Date.now()}-${index}`,sourceIndex:index,sourceName:source.sourceName,label:source.sourceName,included:true,password:false,truncate:false};app.staged.fields.push(field);app.staged.mappings[field.id]=source.sourceName});renderImportFields()}}
function showImport(data){if(data.kind==="pdf"){$("#pdfFrame").src=data.url;$("#pdfDialog").showModal();return}app.staged=prepareImport(data);$("#importName").textContent=data.sourceName;$("#importSheet").innerHTML=[...data.sheets].reverse().map(s=>`<option ${s===data.sheet?"selected":""}>${esc(s)}</option>`).join("");$("#excludeHidden").checked=data.excludeHidden!==false;$("#importMode").value=app.workspace.importPreferences?.mode||"replace";$("#importCount").textContent=`${data.rows.length} rows ready${data.hiddenRows?` · ${data.hiddenRows} hidden in sheet`:""}`;renderImportFields();if(!$("#importDialog").open)$("#importDialog").showModal()}
function commitImport(){const d=app.staged;if(!d)return;const mapped=Object.values(d.mappings).filter(Boolean);if(!mapped.length)return toast("Map at least one Excel column",true);const append=$("#importMode").value==="append",stamp=Date.now(),byName=new Map(d.sourceColumns.map(c=>[nameKey(c.sourceName),Number(c.sourceIndex)])),length=Math.max(0,...d.fields.map(c=>Number(c.sourceIndex)+1));const incoming=d.rows.map((raw,i)=>{const values=Array(length).fill("");d.fields.forEach(field=>{const source=byName.get(nameKey(d.mappings[field.id]));if(source!==undefined)values[field.sourceIndex]=raw.values[source]||""});return{...raw,id:`import-${stamp}-${i}`,values}});applyFillRules(incoming,d.fields);const preferences={...app.workspace.mappingPreferences};d.fields.forEach(field=>{if(d.mappings[field.id])preferences[nameKey(field.sourceName)]=d.mappings[field.id]});app.workspace={...app.workspace,sourceName:d.sourceName,sheets:d.sheets,sheet:d.sheet,headers:d.fields.map(c=>c.sourceName),columns:d.fields,mappingPreferences:preferences,rows:append?[...app.workspace.rows,...incoming]:incoming,rules:append?app.workspace.rules:[],importPreferences:{excludeHidden:$("#excludeHidden").checked,mode:$("#importMode").value}};app.selected.clear();app.page=0;$("#importDialog").close();changed();toast(`${incoming.length} rows imported`)}
async function upload(file){if(!file||app.busy)return;busy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));showImport(await api("/api/import",{name:file.name,data:btoa(binary),excludeHidden:app.workspace.importPreferences?.excludeHidden!==false}))}catch(e){toast(e.message,true)}finally{busy(false)}}
async function switchStaged(){if(!app.staged)return;try{app.staged=await api("/api/sheet",{sheet:$("#importSheet").value,excludeHidden:$("#excludeHidden").checked});showImport(app.staged)}catch(e){toast(e.message,true)}}
async function latest(){busy(true);try{showImport(await api("/api/latest",{}))}catch(e){toast(e.message,true)}finally{busy(false)}}
async function generate(exporting){busy(true);try{const data=await api(exporting?"/api/export":"/api/render",{workspace:job()});app.output=data;$("#pdfFrame").src=data.url;$("#pdfDialog").showModal();if(exporting){const t=$("#outputTicket");t.hidden=false;t.href=data.downloadUrl;$("#outputName").textContent=data.name;$("#outputPath").textContent=data.path;toast(`Exported ${data.slips} slips`)}return data}catch(e){toast(e.message,true)}finally{busy(false)}}
async function ensureOutput(){return app.output||generate(true)}

async function init(){try{const s=await api("/api/state");app.defaults=s.defaults;app.fonts=s.fonts;app.latest=s.latestWorkbook;app.workspace=hydrate(s.workspace,s.defaults);$$('[data-font]').forEach(el=>el.innerHTML=app.fonts.map(f=>`<option>${esc(f)}</option>`).join(""));wire();render()}catch(e){document.body.innerHTML=`<main class="fatal"><b>Could not start</b><span>${esc(e.message)}</span></main>`}}
function wire(){
  $("#fileButton").onclick=()=>$("#fileInput").click();$("#emptyImportButton").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>{upload(e.target.files[0]);e.target.value=""};$("#latestButton").onclick=latest;
  $$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.toggle("active",x===b));$$('[data-pane]').forEach(x=>x.classList.toggle("active",x.dataset.pane===b.dataset.view));$("#rowTools").style.visibility=b.dataset.view==="rows"?"visible":"hidden"});
  $("#fieldsButton").onclick=()=>togglePanel("fieldsPanel");$("#rulesButton").onclick=()=>togglePanel("rulesPanel");$$('.close-panel').forEach(b=>b.onclick=()=>b.closest(".popover").hidden=true);
  $("#rowSearch").oninput=renderTable;$("#addRowButton").onclick=()=>{const length=Math.max(app.workspace.headers.length,...app.workspace.columns.map(c=>Number(c.sourceIndex)+1),0);app.workspace.rows.push({id:`new-${Date.now()}`,rowNumber:"",values:Array(length).fill(""),included:true,added:true});changed()};
  $("#bulkApply").onclick=()=>{const i=Number($("#bulkColumn").value),v=$("#bulkValue").value;app.workspace.rows.filter(r=>app.selected.has(r.id)).forEach(r=>r.values[i]=v);changed()};$("#includeSelected").onclick=()=>setSelected(true);$("#excludeSelected").onclick=()=>setSelected(false);$("#deleteSelected").onclick=()=>{app.workspace.rows=app.workspace.rows.filter(r=>!app.selected.has(r.id));app.selected.clear();changed()};
  $("#ruleColumn").onchange=ruleValues;$("#addRuleButton").onclick=()=>{const op=$("#ruleOperator").value,value=$("#ruleValue").value.trim(),index=Number($("#ruleColumn").value),column=sourceColumn(index);if(op!=="empty"&&!value)return toast("Choose or type a value",true);app.workspace.rules.push({columnName:column?.sourceName||"",columnIndex:index,operator:op,value});$("#ruleValue").value="";changed()};$("#saveRuleSetButton").onclick=()=>{const name=$("#ruleSetName").value.trim();if(!name||!app.workspace.rules.length)return toast("Add rules and give the set a name",true);app.workspace.savedRuleSets.push({name,rules:JSON.parse(JSON.stringify(app.workspace.rules))});$("#ruleSetName").value="";changed()};
  $$('[data-design]').forEach(el=>el.oninput=e=>{app.workspace.design[e.target.dataset.design]=e.target.type==="checkbox"?e.target.checked:(e.target.type==="number"||e.target.type==="range"?Number(e.target.value):e.target.value);changed(false)});$("#blankSlips").oninput=e=>{app.workspace.blankSlips=Math.max(0,Number(e.target.value)||0);changed(false)};$("#outputFolder").oninput=e=>{app.workspace.outputFolder=e.target.value;changed(false)};$("#emailAddress").oninput=e=>{app.workspace.emailAddress=e.target.value;changed(false)};$("#extraSummaryColumns").oninput=e=>{app.workspace.extraSummaryColumns=e.target.value.split(",").map(x=>x.trim()).filter(Boolean);changed(false)};
  $("#previousPreview").onclick=()=>{app.page=Math.max(0,app.page-1);queuePreview()};$("#nextPreview").onclick=()=>{app.page++;queuePreview()};$("#previewPdfButton").onclick=()=>generate(false);$("#exportButton").onclick=()=>generate(true);$("#openButton").onclick=async()=>{const d=await ensureOutput();if(d)api("/api/open",{kind:"export"}).catch(e=>toast(e.message,true))};$("#emailButton").onclick=async()=>{const d=await ensureOutput();if(d)api("/api/email",{emailAddress:app.workspace.emailAddress,sheet:app.workspace.sheet}).catch(e=>toast(e.message,true))};$("#closePdf").onclick=()=>$("#pdfDialog").close();
  $("#importSheet").onchange=switchStaged;$("#excludeHidden").onchange=switchStaged;$("#confirmImport").onclick=commitImport;$("#importDialog").onkeydown=e=>{if(e.key==="Enter"&&e.target.tagName!=="BUTTON"){e.preventDefault();commitImport()}};
  let depth=0;document.addEventListener("dragenter",e=>{if([...e.dataTransfer.types].includes("Files")){depth++;$("#dropOverlay").hidden=false}});document.addEventListener("dragleave",()=>{if(--depth<=0){depth=0;$("#dropOverlay").hidden=true}});document.addEventListener("dragover",e=>e.preventDefault());document.addEventListener("drop",e=>{e.preventDefault();depth=0;$("#dropOverlay").hidden=true;upload(e.dataTransfer.files[0])});
  document.addEventListener("keydown",e=>{const command=e.metaKey||e.ctrlKey,key=e.key.toLowerCase();if(command&&key==="k"){e.preventDefault();$("#rowSearch").focus()}if(command&&key==="o"){e.preventDefault();$("#fileInput").click()}if(command&&key==="e"){e.preventDefault();generate(true)}if(command&&e.key==="Enter"){e.preventDefault();generate(false)}if(e.key==="Escape")$$('.popover').forEach(p=>p.hidden=true)});
}
function setSelected(value){app.workspace.rows.filter(r=>app.selected.has(r.id)).forEach(r=>r.included=value);changed()}
function togglePanel(id){$$('.popover').forEach(p=>{if(p.id!==id)p.hidden=true});const p=$("#"+id);p.hidden=!p.hidden}
init();
